### ISSUE TITLE
Confirm that Database implementation of Rust works on Android

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-android-sdk#11]
# What

Database Layer which includes CoreDb and RangeDb. These require Interface and its implementation.
Confirm that Database implementation of Rust works on Android.

# Note

https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/34

**Comment by omuomugin** [comment]
https://developer.android.com/jetpack/androidx/releases/room

This might be a good reference.
However we should discuss how much library can depend on `androidx` which is android official support library.

**Comment by syuhei176** [comment]
changed description
