### ISSUE TITLE
Implement Singleton Database Manager

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-android-sdk#24]
Singleton Database Manager is accessed from Rust layer.
Rust implementation is [here](https://github.com/cryptoeconomicslab/plasma-rust-framework/blob/master/db/src/impls/kvs/memory.rs). But we should build minimal spec in this issue.

**Comment by omuomugin** [comment]
[Memo]
in #11 I pointed out Room which is database layer library for android.
However it has lot of dependencies issue, so it would be good to use lowest api for sql (like [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper)) this would be core package so there are only few dependency issue.

**Comment by omuomugin** [comment]
This is already done in #28
