### ISSUE TITLE
Design demo application

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-android-sdk#40]
Let's make design for demo application following [screen flow](https://github.com/cryptoeconomicslab/plasma-android-sdk/issues/39).
until Sep 20.

**Comment by tkmct** [comment]
Writing screen flow for demo application for real use case.

## purpose
To show OVM functionality in real use case.

## features
- Basic wallet feature
  - Account balance
  - Address
  - deposit, exit
- Payment
  - Send
  - History (Send, Receive)
- Dex
  - New offer
  - Offer List
  - Exchange
- Game?(no idea)

**Comment by omuomugin** [comment]
So should I do this ?
I can try doing it with sketch file you created.

If yes just assign me.

**Comment by tkmct** [comment]
@omuomugin Issue for implementating frontend is #44

**Comment by tkmct** [comment]
https://www.figma.com/file/FFky7nwWtXd4QalbGEWTrF/PlasmaWalletMock?node-id=0%3A1
