### ISSUE TITLE
Figure it out why rust building is failing

### ISSUE THREAD

**Issue by omuomugin** [cryptoeconomicslab/plasma-android-sdk#7]
# What
Right now
https://github.com/cryptoeconomicslab/plasma-android-sdk/pull/5#discussion_r296433080
https://github.com/cryptoeconomicslab/plasma-android-sdk/pull/5#discussion_r296433099

it is failing to build so figure it out why it fails and fix the issue.

**Comment by omuomugin** [comment]
# Reference
https://github.com/rust-lang/backtrace-rs/issues/161

my error message is saying 

```
failed to run custom build command for `backtrace-sys v0.1.29`

error occurred: Failed to find tool. Is `i686-linux-android-clang` installed?
```

and 

```
failed to run custom build command for `backtrace-sys v0.1.29`

error occurred: Failed to find tool. Is `arm-linux-androideabi-clang` installed?

```

**Comment by syuhei176** [comment]
maybe related to [this](https://github.com/rust-lang-nursery/failure/issues/246)?
